/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ResCard {
        "description": string;
        "headline": string;
        "imageUrl": string;
    }
    interface ResCardLayout {
    }
    interface ResTab {
        "active": boolean;
        "name": string;
    }
    interface ResTabs {
        "active": string;
        "align": string;
    }
}
declare global {
    interface HTMLResCardElement extends Components.ResCard, HTMLStencilElement {
    }
    var HTMLResCardElement: {
        prototype: HTMLResCardElement;
        new (): HTMLResCardElement;
    };
    interface HTMLResCardLayoutElement extends Components.ResCardLayout, HTMLStencilElement {
    }
    var HTMLResCardLayoutElement: {
        prototype: HTMLResCardLayoutElement;
        new (): HTMLResCardLayoutElement;
    };
    interface HTMLResTabElement extends Components.ResTab, HTMLStencilElement {
    }
    var HTMLResTabElement: {
        prototype: HTMLResTabElement;
        new (): HTMLResTabElement;
    };
    interface HTMLResTabsElement extends Components.ResTabs, HTMLStencilElement {
    }
    var HTMLResTabsElement: {
        prototype: HTMLResTabsElement;
        new (): HTMLResTabsElement;
    };
    interface HTMLElementTagNameMap {
        "res-card": HTMLResCardElement;
        "res-card-layout": HTMLResCardLayoutElement;
        "res-tab": HTMLResTabElement;
        "res-tabs": HTMLResTabsElement;
    }
}
declare namespace LocalJSX {
    interface ResCard {
        "description"?: string;
        "headline"?: string;
        "imageUrl"?: string;
    }
    interface ResCardLayout {
    }
    interface ResTab {
        "active"?: boolean;
        "name"?: string;
    }
    interface ResTabs {
        "active"?: string;
        "align"?: string;
    }
    interface IntrinsicElements {
        "res-card": ResCard;
        "res-card-layout": ResCardLayout;
        "res-tab": ResTab;
        "res-tabs": ResTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "res-card": LocalJSX.ResCard & JSXBase.HTMLAttributes<HTMLResCardElement>;
            "res-card-layout": LocalJSX.ResCardLayout & JSXBase.HTMLAttributes<HTMLResCardLayoutElement>;
            "res-tab": LocalJSX.ResTab & JSXBase.HTMLAttributes<HTMLResTabElement>;
            "res-tabs": LocalJSX.ResTabs & JSXBase.HTMLAttributes<HTMLResTabsElement>;
        }
    }
}
